// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

type Player struct {
	ID        int32  `json:"id"`
	UserID    int32  `json:"user_id"`
	Name      string `json:"name"`
	BestScore int32  `json:"best_score"`
	Color     int32  `json:"color"`
}

type User struct {
	ID           int32  `json:"id"`
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
}
